### ISSUE TITLE
[breach-resolution] "Mark as resolved" in unstyled when returning to a solved breach

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#1506] opened 2020-01-26 06:31 UTC
I assume the idea is to show it as disabled, but right now it's just text

<img width="202" alt="Schermata 2020-01-26 alle 07 29 06" src="https://user-images.githubusercontent.com/3644868/73131580-e17c6580-400d-11ea-9a40-a190f965b9a6.png">

vs

<img width="255" alt="Schermata 2020-01-26 alle 07 31 24" src="https://user-images.githubusercontent.com/3644868/73131585-e5a88300-400d-11ea-825f-b17f16327d5d.png">

**Comment by lesleyjanenorton** [comment] 2020-01-28 09:58
Related to #1512.  
This is actually as designed, but perhaps a disabled button would be clearer? @changecourse what are your thoughts here?
<img width="1554" alt="Screen Shot 2020-01-28 at 3 54 28 AM" src="https://user-images.githubusercontent.com/22355127/73253408-19a4b500-4182-11ea-880b-317cd0277a1c.png">

**Comment by changecourse** [comment] 2020-02-10 17:19
The goal with the "marked as resolved" state was to de-emphasize the rows associated with emails that you have already resolved, while maintaining the stronger calls-to-action blue buttons for unresolved emails. 

I'm open to alternate approaches if we feel like this is confusing, but I may need some additional context for understanding.

**Comment by EMMLynch** [comment] 2024-03-07 15:58
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Closed by EMMLynch** 2024-03-07 15:58 UTC
Labels: front-end, needs-UX, feature-breach-resolution
