### ISSUE TITLE
List of email addresses changes based on Firefox Account's primary email address

### ISSUE THREAD

**Issue by cparker15** [mozilla/blurts-server#1624] opened 2020-03-30 00:51 UTC
My Firefox Account has a primary email address (`Address A`) and a secondary email address (`Address B`). This can be seen by visiting https://accounts.firefox.com/settings/emails.

When I sign in to Firefox Monitor while my Firefox Account's primary email address is `Address A` and visit https://monitor.firefox.com/user/preferences, I see a list of all of the email addresses that I have added to Firefox Monitor beneath the *Email Addresses* heading, separated into two sections: *Firefox Account Email - Primary* and *Other Monitored Emails*. `Address A` appears in the *Firefox Account Email - Primary* section, and `Address B` appears among the list of *Other Monitored Emails*. I have already added the maximum number of emails that can be monitored according to the Firefox Monitor's design, so I do not see an *Add a new email address* section beneath the *Other Monitored Emails* section. Everything is working as expected so far.

When I sign out of Firefox Monitor, go back to https://accounts.firefox.com/settings/emails and make `Address B` my Firefox Account's primary email address, and then return to Firefox Monitor and visit https://monitor.firefox.com/user/preferences again, I don't see a list of all of the email addresses that I have added to Firefox Monitor. Instead, beneath the *Email Addresses* heading, the *Other Monitored Emails* section is missing. Instead, I see the *Firefox Account Email - Primary* section, which predictably displays `Address B`, and, in place of the *Other Monitored Emails* section, I see an *Add a new email address* section displaying a text input field and a blue *Send Verification Link* button.

It seems like Firefox Monitor is using the Firefox Account's primary email address as a primary key, instead of a property of the Firefox Account that does not have any semantic meaning embedded in it, such as a UUID. Would it be possible to change the relationship between Firefox Account and Firefox Monitor to use a unique and meaningless property, instead?

**Comment by groovecoder** [comment] 2020-03-30 13:01
Sounds like a dupe of https://github.com/mozilla/blurts-server/issues/1349 ? Can you upvote that one and and a link to this issue for your details?

**Closed by groovecoder** 2020-03-30 13:01 UTC
