### ISSUE TITLE
A few warnings via Pontoon site

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#564] opened 2018-10-29 23:38 UTC
https://pontoon.mozilla.org/projects/firefox-monitor-website/

> **WARNINGS: 4**

So I tweaked my [**pontoonql**](https://github.com/pdehaan/pontoonql) library to work with the CLI so I could fumble w/ filtering via **jq**:

```sh
$ npx pdehaan/pontoonql firefox-monitor-website | jq '.[] | select(.stringsWithWarnings!=0) | {locale: .locale.code, warnings: .stringsWithWarnings}'

{
  "locale": "cs",
  "warnings": 3
}
{
  "locale": "id",
  "warnings": 1
}
```

This tells me that 3 warnings are in the [Czech (cs)](https://pontoon.mozilla.org/cs/firefox-monitor-website/all-resources/?status=warnings&string=191938) locale:

> - Missing message reference: `-brand-name`
> - Obsolete message reference: `-product-name`
> - Obsolete message reference: `-product-name`

And 1 warning in the [Indonesian (id)](https://pontoon.mozilla.org/id/firefox-monitor-website/all-resources/?status=warnings&string=191979) locale:

> - Missing message reference: `no-breaches`

**Comment by flodolo** [comment] 2018-10-30 19:34
The ones in cs are probably expected. Names should be adapted to case, but that's not possible for brands, so they yipically replace it with nouns like application, browser, etc.

The one from Indonesian is caused by a bug in Pontoon that I should be able to fix. In general, we'll need to look out for missing [0] forms across languages :-\

I'll try to take time to go through the translations we have so far.

As for flagging them, going through me is usually a good first step.

**Comment by flodolo** [comment] 2018-10-30 19:36
One more note: compare-locales warnings show up in Pontoon too.

**Comment by groovecoder** [comment] 2019-01-15 01:37
I'm going to close this, as the warnings show up in Pontoon, which seems like the best channel for flagging, communicating, and fixing these issues.

**Closed by groovecoder** 2019-01-15 01:37 UTC
Labels: bug, l10n
