### ISSUE TITLE
Deleting a secondary email issues an application error

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#890] opened 2019-05-09 15:38 UTC

**Comment by groovecoder** [comment] 2019-05-10 19:54
I was unable to reproduce this error on either https://monitor-v2.herokuapp.com/user/preferences or on my http://localhost:6060/user/preferences. (It may have been fixed by https://github.com/mozilla/blurts-server/pull/897? ) I'm going to close this to focus on things I can reproduce.

If you (or QA) can find the reliable steps-to-reproduce this, please re-open.

**Closed by groovecoder** 2019-05-10 19:54 UTC
Labels: :bug: bug, :email: feature-email

**Comment by pdehaan** [comment] 2019-05-10 20:38
I'm not logged in to FxA on monitor-v2, but I seem to be getting an application error when visiting https://monitor-v2.herokuapp.com/user/preferences (but not the homepage of the server, which makes me think the server is alive).

**Comment by groovecoder** [comment] 2019-05-10 21:17
@pdehaan can you file that as a separate issue? Basically, "Visiting /user/preferences without a session triggers an application error" ?
