### ISSUE TITLE
The backgrounds of some boxes wrongly link to the same links as the buttons they contain

### ISSUE THREAD

**Issue by heres-maria** [mozilla/blurts-server#1661] opened 2020-04-24 09:39 UTC
**[Affected Versions]:**
- All

**[Affected Platforms]:**
- All

**[Prerequisites]:**
- You are on https://blurts-server-review.herokuapp.com/
OR
- You are on https://monitor-v2.herokuapp.com/
OR
- You are on https://monitor.firefox.com/

**[Steps to reproduce]:**
1. Click on the white background of the “LATEST BREACH ADDED” box.

**[Expected results]:**
- Nothing happens.

**[Actual results]:**
- You are redirected to the same link as the "See if you were in this breach" text button.

**[Note]:**
- This issue is also reproducible for the breach boxes on the **“/breaches”** and **“/scan”** pages.
- This issue is also reproducible for the “Find out about new data breaches” box (not signed in) or “Bring Firefox to your phone and tablet” box (signed in) on **individual breach pages**.
- While the box is hovered, the mouse pointer also changes to the link pointer.
- This issue is reproducible on all of the available Monitor pages, including in production.
- The header of the latest breach box, containing the “LATEST BREACH ADDED” text, is not affected by this issue.
- This is not reproducible for other boxes on the website.

![link background](https://user-images.githubusercontent.com/53752296/80197872-f45fff80-8627-11ea-9d38-7e39c00920c1.gif)

**Comment by lesleyjanenorton** [comment] 2020-04-28 15:38
Closing - this is intended behavior. Thank you for filing though.

**Closed by lesleyjanenorton** 2020-04-28 15:38 UTC
