### ISSUE TITLE
Hover on breach card unstable

### ISSUE THREAD

**Issue by sandysage** [mozilla/blurts-server#1287] opened 2019-10-21 18:27 UTC
![monitor-card-zooming](https://user-images.githubusercontent.com/850418/67232205-1caf3d00-f3fe-11e9-9a72-abd74d089ced.gif)

**Comment by sandysage** [comment] 2019-10-21 18:30
Closing as a duplicate of #1256

**Comment by changecourse** [comment] 2019-10-21 18:31
This is more pronounced in a disorienting way on Chrome vs. Firefox. 

I think a proposed change to this behavior would be to not zoom the text in the card, but rather just the card itself, keep the cursor change, and keep the darker shadow, on hover.

**Comment by groovecoder** [comment] 2019-10-21 18:42
Hmm ... I can't reproduce this?

**Comment by lesleyjanenorton** [comment] 2019-12-12 19:41
Closed in #1430

**Closed by lesleyjanenorton** 2019-12-12 19:41 UTC
