### ISSUE TITLE
Report from user: ERROR- Verification token is required.

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#526] opened 2018-10-09 22:01 UTC
Potential bug received from user: 

"After I have put in my verification reply, this shows up. ERROR- Verification token is required. Where is my token? I have tried many times and this message shows up."

**Comment by groovecoder** [comment] 2018-10-10 13:35
Have seen a couple reports of this, but I'm not able to reproduce. It may happen if the link visited is:

https://monitor.firefox.com/user/verify
https://monitor.firefox.com/user/verify?token=

It could be that certain email platforms or clients are messing up the link? Will need reliable steps-to-reproduce before we can debug:

* Which email provider
* Which email client

**Comment by tcinotto** [comment] 2018-10-10 15:47
Are we allowed to reach out to a user to help triage?

**Comment by groovecoder** [comment] 2018-10-10 18:37
Individual private email seems fine, but wouldn't include anyone else in case a user doesn't understand that the messages may not be private.

**Comment by groovecoder** [comment] 2018-12-01 16:05
At least 1 user report via email reply includes a link with `verify?token` - so the entire token param value was stripped.

**Comment by groovecoder** [comment] 2019-01-25 02:42
If email clients are stripping url params from hyperlinks, we may be able to reduce the number of these errors by adding a line like: "If the above link does not work, you may copy and paste this url into your browser: <url>"

@sandysage @betsymi ?

**Comment by EMMLynch** [comment] 2024-03-06 19:38
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Closed by EMMLynch** 2024-03-06 19:38 UTC
Labels: defect, feature-email
