### ISSUE TITLE
[Mobile] The "Firefox Monitor" text is not displayed on front page in portrait mode

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1213] opened 2019-09-30 14:18 UTC
## Steps to reproduce
1. Install and Launch the app.
2. Access `https://monitor-v2.herokuapp.com/`

### Expected behavior
The `Firefox Monitor` text is displayed right near the logo.
### Actual behavior
The  `Firefox Monitor` is not displayed.
### Device information

* Android device: `Samsung Galaxy S10+(Android 9), Samsung Galaxy Note 9(Android 8)`
* Fenix version: `Latest Firefox and Chrome` versions.
### Notes
In landscape mode the issue cannot be reproduced.
![Screenshot_20190930-170349_Firefox](https://user-images.githubusercontent.com/42831109/65886452-07b62f80-e3a5-11e9-95c0-fa6ad6ce2863.jpg)
![Screenshot_20190930-170341_Firefox](https://user-images.githubusercontent.com/42831109/65886455-097ff300-e3a5-11e9-9106-e8d1f1966198.jpg)

**Comment by lesleyjanenorton** [comment] 2019-09-30 15:50
Closing since this is as designed. The "Firefox Monitor" logotype should no longer be visible on screen sizes narrower than 450px to make room for the Bento button.

**Closed by lesleyjanenorton** 2019-09-30 15:50 UTC
