### ISSUE TITLE
The Bento Box button is still selected after the menu is closed

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#1253] opened 2019-10-07 11:35 UTC
[Affected Platforms]:
- Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.14

[Steps to reproduce]:
1. Navigate to  https://monitor-v2.herokuapp.com/
2. Click on the Bento Box button.
3. Click on it again and move the cursor away. 

[Expected result]:
- The Bento Box is not selected. 

[Actual result]:
- The Bento Box is still selected and has the hover effect. 

[Regression]:
- N/A

[Additional Notes]:
- This issue is reproducing on Chrome and Firefox. 
- Please look at the attached gif. 
![the button is still selected](https://user-images.githubusercontent.com/42799381/66308305-75b3a700-e90f-11e9-9a22-0bd6abdcd131.gif)

**Comment by pwalm** [comment] 2019-10-07 16:38
I have reproduced this on mobile Safari as well.

**Comment by EMMLynch** [comment] 2024-03-06 21:37
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Closed by EMMLynch** 2024-03-06 21:37 UTC
