### ISSUE TITLE
"See if you were in this breach" is not functional on mobile browsers w/ responsive view

### ISSUE THREAD

**Issue by chrismore** [mozilla/blurts-server#1454] opened 2019-12-20 16:56 UTC
Steps to reproduce:

1) Visit homepage of monitor.firefox.com

2) View "Latest breach added" card

3) Click "See if you were in this breach"

4) Enter your email address

5) Click "Find out"

Expected results:

See results for email at https://monitor.firefox.com/scan

Actual results:

Redirected to https://monitor.firefox.com homepage

This loop will continue forever and you cannot check if you are included in a new breach unless you perform the steps above on desktop OR a desktop view on a mobile device.

**Comment by lesleyjanenorton** [comment] 2019-12-20 17:02
What kind of device/browser? I'm not able to reproduce on an iPhone X using Safari.

**Comment by chrismore** [comment] 2019-12-20 17:02
These steps were reproducible on an Android device on both Firefox mobile and Chrome mobile. Switching to "desktop view" in the browsers functioned as expected.

**Comment by lesleyjanenorton** [comment] 2019-12-20 17:11
So this is strange: I can reproduce this using Firefox for iOS on production, but not on localhost.

**Comment by chrismore** [comment] 2019-12-20 17:16
Maybe it has something to do with server-side redirects?

**Comment by lesleyjanenorton** [comment] 2019-12-20 22:23
@groovecoder any thoughts here? Just tried from @skim1102 's phone (Android - Firefox and Chrome (incognito and normal)) and we were able to reproduce exactly once, but after that everything worked as expected.

**Comment by lesleyjanenorton** [comment] 2019-12-20 22:34
Also happening on Heroku. 302 from Heroku logs:
`2019-12-20T22:27:18.883323+00:00 heroku[router]: at=info method=POST path="/scan" host=fx-breach-alerts.herokuapp.com request_id=4a1b0d17-f1c1-4f0c-96a3-08cd0571fd5c fwd="98.164.32.141" dyno=web.1 connect=0ms service=17ms status=302 bytes=1209 protocol=https`

**Comment by skim1102** [comment] 2019-12-20 23:00
STR:
Check that `emailHash` value is added in the non-mobile browser when POST-ing to `/scan`:
1. On Firefox browser click on "See if you were in this breach" to go to https://fx-breach-alerts.herokuapp.com/?breach=Zynga
2. Open up Network tab on the inspect tool
3. Fill out the form with a sample email address
4. Check the https://fx-breach-alerts.herokuapp.com/scan post call and check that the in the params section the `emailHash` field has a hashed value:
<img width="1437" alt="Screen Shot 2019-12-20 at 4 54 35 PM" src="https://user-images.githubusercontent.com/25109943/71297712-3a3f4b00-234a-11ea-8b88-d541531a52b8.png">
5. Check that the `/scan` post call returns a 200 with the proper response (html page with data breach information)

Check that `emailHash` value is EMPTY in the mobile browser when POST-ing to `/scan`:
1. On Firefox browser click on "See if you were in this breach" to go to https://fx-breach-alerts.herokuapp.com/?breach=Zynga
2. Open up Network tab on the inspect tool
3. Change the view to mobile view
4. Fill out the form with a sample email address
5. Check the https://fx-breach-alerts.herokuapp.com/scan post call and check that the in the params section the `emailHash` field does not have a hashed value and instead it the email field is populated:
<img width="1440" alt="Screen Shot 2019-12-20 at 4 59 58 PM" src="https://user-images.githubusercontent.com/25109943/71297705-33b0d380-234a-11ea-9556-cf7eb55c0f86.png">

6. Check that the `/scan` post call returns a 302 and redirected to the home page.

**Comment by groovecoder** [comment] 2019-12-21 17:17
I couldn't reproduce the empty `emailHash` and `302` in the mobile view in Firefox. :(

**Comment by lesleyjanenorton** [comment] 2019-12-23 17:02
I _think_ this is fixed on https://blurts-server-review.herokuapp.com- if anyone is still able to reproduce from there, please let me know!

**Comment by chrismore** [comment] 2019-12-23 17:03
r+ tested on the heroku instance and works as intended now. Thanks!

**Closed** 2020-01-06 18:56 UTC
Labels: defect
