### ISSUE TITLE
Support Lockwise iOS via Bento

### ISSUE THREAD

**Issue by marniepw** [mozilla/blurts-server#1341] opened 2019-11-05 18:51 UTC
Once Lockwise has their ducks in a row wrt the bento (https://github.com/mozilla-lockwise/lockwise-ios/issues/1100), add proper Adjust links to track MAU.

**Comment by sandysage** [comment] 2019-11-11 23:14
This has turned into a big ball of wax. Lockwise team is navigating this with Adjust which has been blocked due to that external dependency. Will update here once we can move forward on the Lockwise side.

**Comment by marniepw** [comment] 2019-11-14 04:34
Per Kayla, this now works automagically: "No code has changed, but the Adjust universal links for Bento are now working! The Adjust rep said there is a known bug on Apple's end where there can sometimes be issues fetching an updated AASA file? But either way, it's all good now and I have a PR up for it."

**Comment by ddurst** [comment] 2019-11-19 18:26
Update: tl;dr link will need to be tweaked, pending updated info here: https://github.com/mozilla-lockwise/lockwise-ios/issues/1100

**Comment by groovecoder** [comment] 2019-11-22 18:17
I think this is fixed in https://github.com/mozilla/blurts-server/pull/1392 ?

**Comment by groovecoder** [comment] 2019-11-22 18:34
Confirmed this is fixed. Should deploy next week.

**Closed by groovecoder** 2019-11-22 18:34 UTC
Labels: effort: XS, feature-bento, priority: P1

**Comment by SimonBasca** [comment] 2019-11-26 13:45
Tested on iPhone X (13.2.2) on Lockwise 1.7.0 build 3092. Going to the https://monitor.firefox.com/, tapping on the bento menu and choosing Lockwise when:
- Lockwise is installed, the app will open
- Lockwise is not installed, tapping on the link will take me to the Lockwise app in App Store.
