### ISSUE TITLE
[Mobile] The page is still zoomed in after closing the Bento menu

### ISSUE THREAD

**Issue by abodea** [mozilla/blurts-server#1254] opened 2019-10-07 13:29 UTC
## Steps to reproduce
1. Install and Launch the app.
2. Access `https://monitor-v2.herokuapp.com/`
3. Open the Bento menu
4. Zoom In.
5. Tap on the `X` button in order to close the Bento menu.

### Expected behavior
The Bento menu should be dismissed and the displayed page should not be zoomed it.
### Actual behavior
The Bento menu is dismissed but the displayed page is zoomed in.
* Android device: `Samsung Galaxy S10+(Android 9), Samsung Galaxy Tab A(Android 9)`
* Fenix version: `Latest Firefox and Chrome` versions.
### Notes:
For more details please see the attachment.
![20191007_161345](https://user-images.githubusercontent.com/42831109/66315910-60df0f80-e91f-11e9-9c27-132ddad5236b.gif)

**Comment by lesleyjanenorton** [comment] 2019-10-07 16:35
Closing - this is intended behavior and functioning as expected. Thanks!

**Closed by lesleyjanenorton** 2019-10-07 16:35 UTC
Labels: android, iOS, mobile 📱, type: defect
