### ISSUE TITLE
Express Router can be used to modularize the code

### ISSUE THREAD

**Issue by bhavyaagg** [mozilla/blurts-server#28] opened 2018-02-02 08:32 UTC
All the code is present in the server.js file. Instead, we should modularize the code by creating different routes using express Router. 

We can have different routes for user, oauth etc.

**Comment by nhnt11** [comment] 2018-02-02 09:07
This is really a dupe of #16. Thanks for this suggestion, it's one of the options I'm considering.

**Closed by nhnt11** 2018-02-02 09:07 UTC
