### ISSUE TITLE
Wildcards in mailadresses

### ISSUE THREAD

**Issue by bitnapper** [mozilla/blurts-server#1473] opened 2020-01-11 20:49 UTC
I have my own mail domain and give every third party the a unique address. Puting in every single address for every service is very difficult and also not possible due to the limitations of firefox monitor. Id love to be able to monitor all my addresses at @mydomain.tld but this is also not supported. Removing the limit and allowing to add more than one adress would be nice, adding support for a whole mail-domain would be even better.

**Comment by pdehaan** [comment] 2020-01-11 23:08
Thanks for the request, @bitnapper!
I believe this might be a duplicate of #1137 (if you wanted to 👍 and subscribe to that issue).

❤️

**Comment by groovecoder** [comment] 2020-01-14 18:07
Dupe of https://github.com/mozilla/blurts-server/issues/1137

**Closed by groovecoder** 2020-01-14 18:07 UTC

**Comment by bitnapper** [comment] 2020-01-15 19:09
Thanks @pdehaan . I did not see the #1137, sorry. It is exactly what I meant.
