### ISSUE TITLE
Cannot check a second email on Chrome on Android

### ISSUE THREAD

**Issue by kuba-orlik** [mozilla/blurts-server#1428] opened 2019-12-04 16:57 UTC
Steps to reproduce:

* open firefox.monitor.com in Chrome on Android
* enter an email address
* the breaches page shows up, as expected
* go to the homepage again
* enter a different address
* nothing happens

Clearing browser cache fixes the issue.

I'm using Firefox Monitor while training people on password security and I've seen the above happen dozens of times.

**Comment by ddurst** [comment] 2019-12-10 18:16
I can't reproduce this on Android 8.0.0, Samsung S9, Chrome 78.

@kuba-orlik Can you give us similar details about your device? And perhaps any unusual settings in Chrome (or how you went back to the homepage (back button vs explicit navigation))?

For what it's worth, it works for me regardless of how I return to the scan page.

**Comment by kuba-orlik** [comment] 2019-12-11 09:01
Unfortunately I can't reproduce it on my own device, but it happened so many times to participants of my workshops that I thought it's good to report it. I'll ask for specific details next time I encounter it in the wild

**Comment by groovecoder** [comment] 2019-12-11 12:47
Closing unless/until we have STR. Thanks for filing though - we'll keep an eye out for this.

**Closed by groovecoder** 2019-12-11 12:47 UTC
Labels: defect, needs-reproduce
