### ISSUE TITLE
On focus - animation is janky

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1419] opened 2019-11-28 12:45 UTC
[Affected versions]:
 - Firefox 71

[Affected Platforms]:
- Windows 10 x64
- MacOS 10.14
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to: https://monitor-v2.herokuapp.com/
2. In the upper side of the page, click on "Breaches"
3. Move your mouse over the existing breaches 

[Expected result]:
The existing breaches are properly displayed on mouse hover.

[Actual result]:
On mouse hover, the animation is janky. 

![IssueBreaches](https://user-images.githubusercontent.com/56026823/69807343-bb913b00-11ed-11ea-9d1d-5d155af00a0f.gif)

**Comment by pdehaan** [comment] 2019-11-29 19:24
Not sure if this is related to (or dupe of) #1287.

**Closed** 2019-12-10 12:46 UTC
