### ISSUE TITLE
The user is redirected to the Firefox Monitor homepage after refreshing the unsubscribe page

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#355] opened 2018-09-06 09:11 UTC
[Affected versions]:
- latest Nightly 64.0a1
- Beta 63.0b3
- Release 62.0

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Prerequisites]:
- the user is already subscribed and has the "Firefox Monitor: Unsubscribe" page displayed

[Steps to reproduce]:
1. Refresh the "Firefox Monitor: Unsubscribe" page.

[Expected result]:
- The "Firefox Monitor: Unsubscribe" page remains displayed.

[Actual result]:
- The user is redirected to Firefox Monitor homepage.

[Regression]:
- Not a regression.

[Additional info]:
- see screencast
![hf](https://user-images.githubusercontent.com/24842369/45147362-6d99ad00-b1cd-11e8-87b0-934a5ee34e74.gif)

**Comment by groovecoder** [comment] 2018-09-06 14:52
Note: this is the fix for https://github.com/mozilla/blurts-server/issues/316.

@jsavory - what should the user see if they refresh the unsubscribe page?

**Comment by groovecoder** [comment] 2018-09-12 21:19
This is closed as of https://github.com/mozilla/blurts-server/pull/406.

Note: the intended behavior is now that refreshing the unsubscribe form after submitted feedback *should show the user an error*

**Closed by groovecoder** 2018-09-12 21:19 UTC
Labels: [QA]: Major issue, needs: UX

**Comment by jvehent** [comment] 2018-09-13 12:34
> should I be this paranoid?

Probably. User enumerations aren't the worst of attacks, but since this is a security service, I think it's fair to take extra precautions.

**Comment by nhnt11** [comment] 2018-09-13 13:05
Cool, @groovecoder, I didn't mean to draw attention to the language, I was just using that phrase to identify the view I was talking about :) Anyway, looks like this has been taken care of!
