### ISSUE TITLE
Signing in results in must-be-signed-in error

### ISSUE THREAD

**Issue by past** [mozilla/blurts-server#1067] opened 2019-06-04 19:57 UTC
This happens consistently for me:
1. Open https://blog.mozilla.org/blog/2019/06/04/firefox-now-available-with-enhanced-tracking-protection-by-default/ (or any of the other blog posts from today's launch)
2. Clicking on the last link in the article ("We invite you to check out the new breach dashboard on Firefox Monitor!")
3. Click Sign In on the top right of the page, or Log-in further down the page.
4. Sign in to a Firefox Account
5. You find yourself in the dashboard page with the error "must-be-signed-in":
![Screenshot_2019-06-04 Find out if you’ve been part of a data breach](https://user-images.githubusercontent.com/49118/58909522-30187080-86c8-11e9-8d67-a0ca6bcb3d0d.png)
Reloading the page fixes it.

**Comment by groovecoder** [comment] 2019-06-04 20:06
I was unable to reproduce this. Do you happen to be using Containers? Did you maybe "cross a container boundary" during the Sign in flow?

**Comment by past** [comment] 2019-06-04 20:08
I've seen this in both a container tab and a private browsing window. No container boundary crossing happened as far as I can tell.

**Comment by past** [comment] 2019-06-04 20:09
Oh, by the way, this is in Nightly with Content Blocking: Standard.

**Comment by pdehaan** [comment] 2019-06-04 21:15
Interesting. I was unable to repro on macOS w/ Nightly (2019-06-04) in regular and private window or w/ Content Blocking: Standard (with a new profile).

**Comment by angejens** [comment] 2019-07-17 20:04
I have the same problem and think it might be due to adding too many email addresses to be monitored.  In my original account, I have 10 email addresses to be monitored.  I created a second account and had no problems until I added the 9th email address.  I tried this in Firefox and Google Chrome and got the error, but did not have problems with Edge

**Comment by congqiao** [comment] 2019-07-17 20:45
The same issue happens to me consistently on Firefox/Chrome on macOS/Windows. I also added more than 10 email addresses when I initially set up Firefox Monitor. After the initial setup, I get this error every time I log in.

**Comment by groovecoder** [comment] 2019-07-18 02:49
Oh, interesting the 10 email addresses bit of information might be a clue here.

**Comment by lissyx** [comment] 2019-07-25 16:57
> Oh, interesting the 10 email addresses bit of information might be a clue here.

It also happened to me after adding addresses as documented in #1146. More than 10, I can't tell how many though.

**Comment by rfk** [comment] 2019-07-25 22:56
> Oh, interesting the 10 email addresses bit of information might be a clue here.

Yep: https://github.com/mozilla/blurts-server/issues/1084#issuecomment-515242813

**Comment by past** [comment] 2019-07-25 23:36
I should probably mention that I only have 3 email addresses associated with Monitor.

**Comment by rfk** [comment] 2019-07-26 00:14
@past could you please try a fresh signin to Monitor and watch the network console to capture the redirect from `/oauth/confirmed` at the end of the flow? I would be interested to see if it is also trying to set a large cookie as described in https://github.com/mozilla/blurts-server/issues/1084#issuecomment-515242813, perhaps due to some other large quantity of data in your profile (such as FxA profile data).

**Comment by pdehaan** [comment] 2019-07-29 21:21
Fixed via #1149

**Closed by pdehaan** 2019-07-29 21:21 UTC
Labels: :bug: bug

**Comment by groovecoder** [comment] 2019-07-31 17:01
The fix for this issue is now deployed. Thank you everyone for your patience!
