### ISSUE TITLE
There is an inconsistency between zoom in and zoom in text only when viewing the Monitor Sign Up Promo and Firefox Mobile Promo

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#1593] opened 2020-03-17 13:22 UTC
Affected versions]:
-  Firefox 74.0

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 18.04 x64

[Steps to reproduce]:
1. Navigate to https://blurts-server-review.herokuapp.com/
2. Without signing in, enter any email address (ex. john@mailinator.com) and click on "Check for Breaches" button.
3. Click on any of the breaches.
4. Zoom in and observe the behaviour.
5. Select "Zoom Text Only" (Menu bar -> View -> Zoom -> Zoom Text Only).
6. Zoom in and observe behaviour. 

[Expected result]:
- The banners has the same format. 

[Actual result]:
- The banners are different. 

[Regression]:
- N/A

[Additional Info]:
- This issue is reproducing with "Firefox Mobile Promo" banner too. Only there the QR Code disappears as well. 
- Please look at the attached images: 

Zoom in:
![Screenshot from 2020-03-17 15-17-07](https://user-images.githubusercontent.com/42799381/76859840-b6223400-6862-11ea-9447-3b121a3cde47.png)

Zoom in Text Only:
![Screenshot from 2020-03-17 15-17-37](https://user-images.githubusercontent.com/42799381/76859868-c0443280-6862-11ea-912c-a7e46baebebd.png)

**Comment by lesleyjanenorton** [comment] 2020-03-25 02:45
Are you able to reproduce this ? I haven't been able to in macOS or Windows (Parallels).

**Comment by obotisan** [comment] 2020-03-27 13:12
Yes, I can still reproduce the issue. Please look at the attached gif:
![difference between zooms](https://user-images.githubusercontent.com/42799381/77759389-53d4ea80-703d-11ea-922b-c1098f7a2238.gif)

**Comment by EMMLynch** [comment] 2024-03-08 15:54
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Closed by EMMLynch** 2024-03-08 15:54 UTC
Labels: defect, effort-XS, needs-reproduce, feature-contextual-recommendations
