### ISSUE TITLE
The tab key navigation is influenced by the zoom level of the browser

### ISSUE THREAD

**Issue by sbadau** [mozilla/blurts-server#1251] opened 2019-10-04 13:13 UTC
[Affected versions]:

- Firefox 69.0.2
- not reproducible on Chrome or on Safari

[Affected Platforms]:

- Windows 10 x64, macOS 10.14 and Ubuntu 18.04

[Steps to reproduce]:

1. Navigate to the Monitor website "https://monitor-v2.herokuapp.com/".
2. CIick the "bento menu" button.
3. Hit the tab key once.
4. Close the "bento menu".
5. Click the "bento menu" again and Zoom in, around 200% - use the keyboard shortcut Ctrl++
6. Use the Tab key to reach the Firefox Send option.

[Expected result]:
In step 3 - the Firefox Send option is focused after one tab.
In step 6 - the Firefox Send option is focused after one Tab.

[Actual result]:
In step 3 - the Firefox Send option is focused after one tab.
In step 6 - the Firefox Send option is focused after two tabs - the first tab focuses the FxA modal and only the second one focuses the option Firefox Send. Also the FxA modal flickers in the process.

![2019-10-04_12h00_58](https://user-images.githubusercontent.com/56026823/66209779-ce413500-e6c0-11e9-962f-a5bdedf9768b.gif)

**Comment by lesleyjanenorton** [comment] 2019-10-04 16:17
I can't reproduce this.

**Comment by sbadau** [comment] 2019-10-07 14:27
I can still reproduce this issue, on Windows 10 and Ubuntu 18.04 - I reproduce it using the exact steps from the description but, on Mac OS X, the behaviour is slightly different. 
STR for Mac OS X:
1. Navigate to the Monitor website "https://monitor-v2.herokuapp.com/".
2. CIick the "bento menu" button.
3. Hit the tab key until Firefox Send is focused
4. Close the "bento menu".
5. Click the "bento menu" again and Zoom in, around 200% - use the keyboard shortcut Ctrl++
6. Use the Tab key to reach the Firefox Send option.

[Expected result]:
In step 3 - the Firefox Send option is focused after one tab.
In step 6 - the Firefox Send option is focused after one Tab.

[Actual result]:
In step 3 - the Firefox Send option is focused after two tabs. On Windows and Ubuntu, in the default zoom state, the Firefox Send option is reached after only one tab (same behaviour is encountered on Mac OS X when using Chrome)
In step 6 - the Firefox Send option is focused after 3 tabs - the first tab focuses the bento menu button, the second one focuses the FxA modal and only the 3rd one focuses the Firefox Send option.

**Comment by EMMLynch** [comment] 2024-03-06 21:37
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Closed by EMMLynch** 2024-03-06 21:37 UTC
