### ISSUE TITLE
The padding-right for links situated in the footer section has too many pixels

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#350] opened 2018-09-05 21:14 UTC
[Affected versions]:
- latest Nightly 64.0a1
- Beta 63.0b3
- Release 62.0

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox.
2. Go to https://fx-breach-alerts.herokuapp.com/
3. Scroll down the page to footer.
4. Focus any link from the Support or Firefox, and move the mouse hand to the right side, but keeping the same line, until the hand disappear. 
- or simply click on a link and inspect its padding

[Expected result]:
- The padding-right has less pixels. 

[Actual result]:
- The padding-right has too many pixels, it passes the half distance between Support and Firefox's links.

[Regression]:
- Not a regression.

[Additional info]:
- see screenshot:
![screenshot_3](https://user-images.githubusercontent.com/24842369/45121149-e74b7f80-b168-11e8-8ef0-1bcd27d10a73.png)

**Comment by lesleyjanenorton** [comment] 2019-02-04 17:01
Closing - the width increases the elements clickable area and is intended behavior. Thank you for filing though!

**Closed by lesleyjanenorton** 2019-02-04 17:01 UTC
Labels: [QA]: Minor issue
