### ISSUE TITLE
Sign in vs Sign Up

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-server#752] opened 2019-02-07 21:51 UTC
![firefox_monitor___scan_results](https://user-images.githubusercontent.com/557895/52445101-074bea00-2adf-11e9-993b-f3576b3566cc.png)

https://github.com/mozilla/blurts-server/blob/ef5e38158634c7783f5ac625fbca4d81408eb1a6/locales/en/app.ftl#L137

https://github.com/mozilla/blurts-server/blob/ef5e38158634c7783f5ac625fbca4d81408eb1a6/locales/en/app.ftl#L280-L281

**Comment by tcinotto** [comment] 2019-02-11 18:30
This is by design. Might be fixed in future design iterations.

**Closed** 2019-02-11 18:30 UTC
Labels: wontfix
