### ISSUE TITLE
“Verify your subscription” dialog could be dismiss automatically after confirming the subscription

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-server#361] opened 2018-09-06 13:47 UTC
[Affected versions]:
- Firefox 62.0
- Firefox 64.0a1

[Affected Platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Click on the "Subscribe" button and write a valid email.
3. Confirm the subscription. 

[Expected result]:
- The “Verify your subscription” dialog could be dismiss automatically and the user can continue the activity on the page.

[Actual result]:
- The “Verify your subscription” dialog is not dismissed automatically. 
 
[Regression]:
- I don't think this is a regression.

**Comment by e-pang** [comment] 2018-09-19 20:45
Once confirmed I don't have a problem with the verify dialog closing

**Comment by EMMLynch** [comment] 2024-03-06 20:11
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.

**Closed by EMMLynch** 2024-03-06 20:11 UTC
Labels: enhancement, needs-UX
