### ISSUE TITLE
Add unsubscribe link to website?

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/blurts-server#697] opened 2019-01-11 15:12 UTC
Does it make sense to surface an unsubscribe link on the website now that we are adding the ability to log in and log out? Should unsubscribes/opt-outs now be handled through the FXA interface?

**Comment by groovecoder** [comment] 2019-01-14 21:59
@sandysage can you weigh in on this?

**Comment by tcinotto** [comment] 2019-04-15 17:22
Will be closed in V2 launch. Duplicate of 849.

**Closed by tcinotto** 2019-04-15 17:22 UTC
Labels: front-end
